name: lord_simulator
description: "Lord Simulator - Krallık Yönetim Oyunu"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

  # Titreşim için
  vibration: ^3.1.3

flutter:
  uses-material-design: true
  
  assets:
    - card/
    - city/
    - city/olaylar/
    - city/olaylar/karisik/
    - events/
    - icon/
    - assets/music/
    - music/

# Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon/file_0000000082b86243a1042895da19c517.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "icon/file_0000000082b86243a1042895da19c517.png"
